import PureFilter from 'appTypes/PureFilter'

const filters: PureFilter[] = [
  {
    id: 0,
    make: 'Toyota',
    modelType: 'Land Cruiser',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 1999,
    yearTo: 2002,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    id: 1,
    make: 'Toyota',
    modelType: 'Land Cruiser',
    priceFrom: 0,
    priceTo: 4500,
    yearFrom: 2003,
    yearTo: 2006,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'Toyota',
    modelType: 'Camry',
    priceFrom: 0,
    priceTo: 1300,
    yearFrom: 2001,
    yearTo: 2006,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'subaru',
    modelType: 'legacy',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 2000,
    yearFrom: 2006,
    yearTo: 2008,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'subaru',
    modelType: 'legacy',
    priceFrom: 0,
    priceTo: 3500,
    yearFrom: 2009,
    yearTo: 2013,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'subaru',
    modelType: 'tribeca',
    priceFrom: 0,
    priceTo: 2500,
    yearFrom: 1990,
    yearTo: 2020,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'skoda',
    modelType: 'octavia',
    priceFrom: 0,
    priceTo: 900,
    yearFrom: 2004,
    yearTo: 2008,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'skoda',
    modelType: 'octavia',
    priceFrom: 0,
    priceTo: 600,
    yearFrom: 2000,
    yearTo: 2004,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'skoda',
    modelType: 'superb',
    priceFrom: 0,
    priceTo: 700,
    yearFrom: 2002,
    yearTo: 2007,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'skoda',
    modelType: 'superb',
    priceFrom: 0,
    priceTo: 2000,
    yearFrom: 2008,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'skoda',
    modelType: 'superb',
    priceFrom: 0,
    priceTo: 2000,
    yearFrom: 2008,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'nissan',
    modelType: 'qashqai',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 2700,
    yearFrom: 1990,
    yearTo: 2020,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'nissan',
    modelType: 'juke',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 3000,
    yearFrom: 1990,
    yearTo: 2020,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'nissan',
    modelType: 'X-trail',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 3000,
    yearFrom: 1990,
    yearTo: 2020,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mitsubishi',
    modelType: 'Shogun Sport',
    priceFrom: 0,
    priceTo: 1200,
    yearFrom: 1990,
    yearTo: 2020,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mitsubishi',
    modelType: 'shogun',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2006,
    yearTo: 2010,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mitsubishi',
    modelType: 'lancer',
    priceFrom: 0,
    priceTo: 800,
    yearFrom: 2006,
    yearTo: 2008,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mitsubishi',
    modelType: 'lancer',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 2000,
    yearFrom: 2009,
    yearTo: 2013,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mitsubishi',
    modelType: 'outlander',
    priceFrom: 0,
    priceTo: 1300,
    yearFrom: 2006,
    yearTo: 2007,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mitsubishi',
    modelType: 'outlander',
    priceFrom: 0,
    priceTo: 1600,
    yearFrom: 2008,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mitsubishi',
    modelType: 'l200',
    priceFrom: 0,
    priceTo: 3000,
    yearFrom: 2006,
    yearTo: 2009,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'lexus',
    modelType: 'rx', //300,
    priceFrom: 0,
    priceTo: 1800,
    yearFrom: 2003,
    yearTo: 2007,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'lexus',
    modelType: 'ls', //460,
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2006,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'honda',
    modelType: 'accord',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1200,
    yearFrom: 2006,
    yearTo: 2008,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'honda',
    modelType: 'accord',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 2000,
    yearFrom: 2008,
    yearTo: 2013,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'chevrolet',
    modelType: 'cruze',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1500,
    yearFrom: 1990,
    yearTo: 2020,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'chevrolet',
    modelType: 'lacetti',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 800,
    yearFrom: 2004,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'hyundai',
    modelType: 'tucson',
    priceFrom: 0,
    priceTo: 900,
    yearFrom: 1990,
    yearTo: 2020,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'skoda',
    modelType: 'octavia',
    priceFrom: 0,
    priceTo: 1300,
    yearFrom: 2009,
    yearTo: 2013,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mazda',
    modelType: 'CX-7',
    priceFrom: 0,
    priceTo: 2000,
    yearFrom: 1990,
    yearTo: 2020,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'volkswagen',
    modelType: 'passat',
    priceFrom: 0,
    priceTo: 900,
    yearFrom: 2005,
    yearTo: 2008,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'subaru',
    modelType: 'impreza',
    priceFrom: 0,
    priceTo: 1600,
    yearFrom: 2008,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'Mercedes-Benz', // need to check
    modelType: 's-class',
    priceFrom: 0,
    priceTo: 3000,
    yearFrom: 2006,
    yearTo: 2010,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '330',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 2300,
    yearFrom: 2005,
    yearTo: 2007,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '325',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1800,
    yearFrom: 2005,
    yearTo: 2007,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '320',
    fuel: 'diesel',
    priceFrom: 0,
    priceTo: 2500,
    yearFrom: 2008,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '318',
    fuel: 'diesel',
    priceFrom: 0,
    priceTo: 2500,
    yearFrom: 2008,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '745',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1500,
    yearFrom: 2002,
    yearTo: 2005,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '530',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1500,
    yearFrom: 2003,
    yearTo: 2006,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '525',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 2000,
    yearFrom: 2006,
    yearTo: 2008,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '730',
    fuel: 'diesel',
    priceFrom: 0,
    priceTo: 2700,
    yearFrom: 2006,
    yearTo: 2008,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '740',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 3000,
    yearFrom: 2006,
    yearTo: 2008,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '545',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 2500,
    yearFrom: 1900,
    yearTo: 2020,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '520',
    fuel: 'diesel',
    priceFrom: 0,
    priceTo: 2000,
    yearFrom: 2007,
    yearTo: 2009,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '540',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1300,
    yearFrom: 1900,
    yearTo: 2020,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '740',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1300,
    yearFrom: 1900,
    yearTo: 2020,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '318',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 2500,
    yearFrom: 2008,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '325',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 2500,
    yearFrom: 2008,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '320',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 2500,
    yearFrom: 2008,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '330',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 3000,
    yearFrom: 2008,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '530',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 2200,
    yearFrom: 2006,
    yearTo: 2008,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
]

export default filters
