import PureFilter from 'appTypes/PureFilter'

const filters: PureFilter[] = [
  {
    make: 'chevrolet',
    modelType: 'lacetti',
    priceFrom: 0,
    priceTo: 800,
    yearFrom: 1990,
    yearTo: 2030,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'chevrolet',
    modelType: 'captiva',
    priceFrom: 0,
    priceTo: 3000,
    yearFrom: 1990,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'chevrolet',
    modelType: 'cruze',
    priceFrom: 0,
    priceTo: 1600,
    yearFrom: 1990,
    yearTo: 2030,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'honda',
    modelType: 'accord',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1600,
    yearFrom: 2006,
    yearTo: 2008,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'honda',
    modelType: 'accord',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 2000,
    yearFrom: 2008,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'honda',
    modelType: 'cr-v',
    priceFrom: 0,
    priceTo: 1600,
    yearFrom: 2006,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'honda',
    modelType: 'civic',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1000,
    yearFrom: 2006,
    yearTo: 2010,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'hyundai',
    modelType: 'tucson',
    priceFrom: 0,
    priceTo: 1000,
    yearFrom: 1990,
    yearTo: 2020,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'lexus',
    modelType: 'rx', //300 && 350,
    priceFrom: 0,
    priceTo: 2500,
    yearFrom: 2003,
    yearTo: 2008,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'lexus',
    modelType: 'ct', //200,
    priceFrom: 0,
    priceTo: 3500,
    yearFrom: 1990,
    yearTo: 2030,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'lexus',
    modelType: 'gs', //300,
    priceFrom: 0,
    priceTo: 1300,
    yearFrom: 1990,
    yearTo: 2030,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mazda',
    modelType: '6',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1500,
    yearFrom: 2008,
    yearTo: 2011,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mazda',
    modelType: '6',
    priceFrom: 0,
    priceTo: 3000,
    yearFrom: 2012,
    yearTo: 2016,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mazda',
    modelType: '3',
    priceFrom: 0,
    priceTo: 3000,
    yearFrom: 2013,
    yearTo: 2016,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mazda',
    modelType: 'cx-5',
    priceFrom: 0,
    priceTo: 3000,
    yearFrom: 1990,
    yearTo: 2030,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mazda',
    modelType: 'cx-7',
    priceFrom: 0,
    priceTo: 3000,
    yearFrom: 1990,
    yearTo: 2030,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mitsubishi',
    modelType: 'lancer',
    priceFrom: 0,
    priceTo: 700,
    yearFrom: 2006,
    yearTo: 2007,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mitsubishi',
    modelType: 'lancer',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1400,
    yearFrom: 2008,
    yearTo: 2011,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mitsubishi',
    modelType: 'outlander',
    priceFrom: 0,
    priceTo: 800,
    yearFrom: 2005,
    yearTo: 2006,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mitsubishi',
    modelType: 'outlander',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 2500,
    yearFrom: 2008,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mitsubishi',
    modelType: 'shogun sport',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1200,
    yearFrom: 1990,
    yearTo: 2030,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'mitsubishi',
    modelType: 'shogun',
    priceFrom: 0,
    priceTo: 2500,
    yearFrom: 2006,
    yearTo: 2010,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'nissan',
    modelType: 'juke',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 2500,
    yearFrom: 2006,
    yearTo: 2010,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'nissan',
    modelType: 'qashqai',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1500,
    yearFrom: 1990,
    yearTo: 2030,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'nissan',
    modelType: 'x-trail',
    priceFrom: 0,
    priceTo: 1800,
    yearFrom: 2008,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'toyota',
    modelType: 'avensis',
    priceFrom: 0,
    priceTo: 2000,
    yearFrom: 2014,
    yearTo: 2017,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'toyota',
    modelType: 'landcruiser',
    priceFrom: 0,
    priceTo: 3000,
    yearFrom: 1998,
    yearTo: 2002,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'toyota',
    modelType: 'rav4',
    priceFrom: 0,
    priceTo: 1600,
    yearFrom: 2006,
    yearTo: 2010,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'skoda',
    modelType: 'octavia',
    priceFrom: 0,
    priceTo: 2000,
    yearFrom: 2013,
    yearTo: 2016,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'skoda',
    modelType: 'octavia',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 800,
    yearFrom: 2004,
    yearTo: 2010,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'skoda',
    modelType: 'superb',
    priceFrom: 0,
    priceTo: 1800,
    yearFrom: 2008,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'skoda',
    modelType: 'yeti',
    priceFrom: 0,
    priceTo: 1600,
    yearFrom: 1990,
    yearTo: 2030,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'suzuki',
    modelType: 'grand vitara',
    priceFrom: 0,
    priceTo: 1500,
    yearFrom: 2005,
    yearTo: 2010,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'renault',
    modelType: 'megane',
    fuel: 'diesel',
    priceFrom: 0,
    priceTo: 1400,
    yearFrom: 2009,
    yearTo: 2015,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'subaru',
    modelType: 'forester',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1300,
    yearFrom: 2006,
    yearTo: 2007,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'subaru',
    modelType: 'forester',
    priceFrom: 0,
    priceTo: 2500,
    yearFrom: 2008,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'subaru',
    modelType: 'impreza',
    priceFrom: 0,
    priceTo: 1300,
    yearFrom: 2008,
    yearTo: 2011,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'subaru',
    modelType: 'outback',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1300,
    yearFrom: 2006,
    yearTo: 2009,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'subaru',
    modelType: 'outback',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1300,
    yearFrom: 2010,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'subaru',
    modelType: 'legacy',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 1300,
    yearFrom: 2006,
    yearTo: 2009,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'subaru',
    modelType: 'legacy',
    fuel: 'petrol',
    priceFrom: 0,
    priceTo: 2000,
    yearFrom: 2010,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '330',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2012,
    yearTo: 2016,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '325',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2012,
    yearTo: 2016,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '320',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2012,
    yearTo: 2016,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '318',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2012,
    yearTo: 2016,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '530',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2010,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '523',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2010,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '524',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2010,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '525',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2010,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '520',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2010,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '518',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2010,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '528',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2010,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '530',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2010,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '535',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2010,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '540',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2010,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '545',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2010,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: '550',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2010,
    yearTo: 2014,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: 'x1',
    priceFrom: 0,
    priceTo: 3500,
    yearFrom: 1990,
    yearTo: 2030,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
  {
    make: 'BMW', // need to check
    modelType: 'x5',
    priceFrom: 0,
    priceTo: 4000,
    yearFrom: 2007,
    yearTo: 2012,
    providers: ['gumtree', 'ebay', 'autotrader'],
  },
]

export default filters
